- hosts: devops
  become: yes

  tasks:
    - name: Copy Docker Compose installation script
      copy:
        src: "../docker-compose.sh"
        dest: "/docker-compose.sh"
        mode: "0755"

    - name: Execute Docker Compose installation script
      shell: /docker-compose.sh
