- hosts: devops
  become: true

  tasks:

    - name: Download Trivy install script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh
        dest: /tmp/trivy-install.sh
        mode: '0755'

    - name: Install Trivy
      ansible.builtin.command:
        cmd: /tmp/trivy-install.sh -b /usr/local/bin v0.72.0
